### ISSUE TITLE
Add ESP8266 support

### ISSUE THREAD

**Issue by grand87** [mongoose-os-libs/ds18b20#1]
ESP 8266 still is a popular chip, would be nice to add support

**Comment by DrBomb** [comment]
Yeah, that's something I've been meaning to do. I'll try to make it happen these following weeks

**Comment by timoschilling** [comment]
any updates on this topic?

**Comment by DrBomb** [comment]
Hi, with the move to `onewire` instead of `onewire-rmt` it should be compatible with all platforms that use `onewire` that includes the esp8266. Closing for now.
