### ISSUE TITLE
ds18b20 stop working on mos version 202102201946

### ISSUE THREAD

**Issue by msukee** [mongoose-os-libs/ds18b20#2]
ds18b20 library stopped working on mos version 202102201946. No errors, just getting DS18B20.get() = 0 all the time.

Something weird is when setting debug_level = 3,  the issue is fixed:  mos config-set debug.level=3

**Comment by DrBomb** [comment]
As a matter of fact, something broke the `onewire-rmt` lib this library depends on. I will port the code to the normal `onewire` lib and push an update. Will close when done, please hang tight!

**Comment by DrBomb** [comment]
Migration complete. Should be working again. I did some preliminary tests, and the code seems fairly simple so there shouldn't be a lot of issues. Let me know if there are some obvious issues.

**Comment by msukee** [comment]
Great!! I will check it out and let you know in case I have problems
Thanks for the prompt response
