### ISSUE TITLE
Getting 0 degree with mgos_ds18b20_get()

### ISSUE THREAD

**Issue by Pela2silveira** [mongoose-os-libs/ds18b20#3]
Using the methods of the library I can´t get the values of the readings, however I can see the readings with debug level in 3.

`  if (mgos_ds18b20_init()){
    temp_int=mgos_ds18b20_get();
  }`

` [Dec 14 10:22:49.679] mgos_ds18b20.c:61       OneWire: DS18B20 Found ADDRESS: 28aaebb24d14119
[Dec 14 10:22:49.679] mgos_ds18b20.c:61       OneWire: DS18B20 Found ADDRESS: 28aaebb24d14119
[Dec 14 10:22:49.679] mgos_ds18b20.c:61       OneWire: DS18B20 Found ADDRESS: 28aaebb24d14119
....
.....
[Dec 14 10:22:50.489] mgos_ds18b20.c:49       OneWire: DS18B20 Reading 23.812500
[Dec 14 10:22:50.520] mgos_ds18b20.c:49       OneWire: DS18B20 Reading 23.812500
[Dec 14 10:22:50.552] mgos_ds18b20.c:49       OneWire: DS18B20 Reading 23.812500
[Dec 14 10:22:50.583] mgos_ds18b20.c:49       OneWire: DS18B20 Reading 23.812500
[Dec 14 10:22:50.615] mgos_ds18b20.c:49       OneWire: DS18B20 Reading 23.812500

....
[Dec 14 10:22:49.569] main.c:53               Int Temp: 0.000000
`

**Comment by DrBomb** [comment]
The init functions on mOS are meant to be called by the system. You should not be calling them yourself. Try it again without calling init before getting the reading. 

Also, remember this library is autonomous and fetches the reading every 5 seconds by default, so account for that. You can lower it if needed on the config.

**Comment by DrBomb** [comment]
Here you can see where it gets set to 0 https://github.com/mongoose-os-libs/ds18b20/blob/master/src/mgos_ds18b20.c#L108 As the init function makes sure we read at least a 0 on init.

**Comment by Pela2silveira** [comment]
Sorry I did´t notice that in mongoose docs. Thank you for your response. I really appreciate that.
